name: "network-monitor__client"

services:
    node:
        container_name: network-monitor__client-node
        build:
            context: .
            target: runner
            dockerfile: ./Dockerfile
        ports:
            - "${DOCKER_HOST_PORT:-3000}:3000"
