name: network-monitor

services:
  database:
    image: 'mysql:9.0.0'
    secrets:
      - database-password
    environment:
      - MYSQL_DATABASE=network-monitor
      - MYSQL_USER=network-monitor
      - MYSQL_PASSWORD=/run/secrets/database-password
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - 'database-data:/var/lib/mysql'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10

  node:
    build:
      context: .
      dockerfile: ./docker/image/node/Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    secrets:
      - database-password
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=network-monitor
      - MYSQL_USER=network-monitor
      - MYSQL_PASSWORD=/run/secrets/database-password
    profiles:
      - base

  node-production:
    extends: node
    build:
      target: production
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - production

  node-development:
    extends: node
    build:
      target: development
    volumes:
      - './public:/usr/src/app/public'
      - './src:/usr/src/app/src'
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - development

secrets:
  database-password:
    file: ./docker/secret/database-password.txt

volumes:
  database-data:
    external: false
