name: network-monitor

services:
  app-database:
    container_name: app-database
    image: mysql:8.3.0
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

      # `MYSQL_ROOT_PASSWORD` variable is required by the MySQL image and should be changed for production environment
      MYSQL_ROOT_PASSWORD: 7RKgi4rYL287o9c69KvpEqx0Ue6KYtS3
    networks:
      - network-monitor
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10

  app-node:
    container_name: app-node
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    networks:
      - network-monitor
    depends_on:
      app-database:
        condition: service_healthy
    profiles: ['base']

  app-node-production:
    container_name: app-node-production
    extends: app-node
    build:
      target: production
    profiles: ['production']

  app-node-development:
    container_name: app-node-development
    extends: app-node
    build:
      target: development
    profiles: ['development']

  app-adminer:
    container_name: app-adminer
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      app-database:
        condition: service_healthy
    profiles: ['development']

networks:
  network-monitor:
    driver: bridge
