name: network-monitor

services:
  database:
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - internal-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
    networks:
      - internal-network
    profiles:
      - base

  node-production:
    extends: node
    build:
      target: production
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - production

  node-development:
    extends: node
    build:
      target: development
    volumes:
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
    depends_on:
      database:
        condition: service_healthy
    profiles:
      - development

volumes:
  database-data:
    external: false

networks:
  internal-network:
    driver: bridge
