name: network-monitor__server

services:
  database:
    image: 'mysql:9.0.0'
    environment:
      - MYSQL_DATABASE=network-monitor
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - 'database:/var/lib/mysql'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10

  server:
    build:
      target: runner
    ports:
      - '8080:8080'
    environment:
      - SERVER_PORT=8080
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=network-monitor
      - DATABASE_USER=root
    depends_on:
      database:
        condition: service_healthy

volumes:
  database:
    external: false
