name: network-monitor

services:
  database:
    image: 'mysql:9.0.0'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - 'database:/var/lib/mysql'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10

  client:
    build:
      context: ../client
      target: production
      args:
        - VITE_API_URL=${API_URL}
    ports:
      - '${CLIENT_APP_PORT}:3000'

  server:
    build:
      context: ../server
      target: production
    ports:
      - '${SERVER_APP_PORT}:${SERVER_APP_PORT}'
    environment:
      - APP_PORT=${SERVER_APP_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      database:
        condition: service_healthy

volumes:
  database:
    external: false
